scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairWest, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level2`)
})
info.startCountdown(10)
let mySprite2 = sprites.create(assets.image`demogorgon`, SpriteKind.Enemy)
let mySprite = sprites.create(img`
    ...............eeeeeee..................
    ..............eeeeeeee..................
    .............eeeeeeeeee.................
    ...............ddfdfd...................
    ...............dddddd...................
    ................ddff....................
    ...............ffddff...................
    .............fffbffbfff.................
    ...........fffeffbbffeff................
    ..........ffeeeefbbfeeeff...............
    ..........feeeeefbbfeeeeff..............
    ..........feeeeefbbfeeeeef..............
    ..........fefeeefbbfeeefef..............
    ..........fefeeefbbfeeefef..............
    ..........fefeeefbbfeeefef..............
    ..........fefeeefbbfeeefef..............
    ..........fefeeffbbffeffff..............
    ..........ffffffbbbbfff.................
    .............fbbbffbbbf.................
    .............fbbbffbbbf.................
    .............fbbffffbbf.................
    .............fbbf..fbbf.................
    .............fbbf..fbbf.................
    .............fbbf..fbbf.................
    .............fbbf..fbbf.................
    .............febf..fbef.................
    ............f11ef..fe11f................
    ...........feeeef..feeeef...............
    ...........ffffff..ffffff...............
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
tiles.setTilemap(tilemap`level1`)
tiles.placeOnRandomTile(mySprite, assets.tile`transparency16`)
scene.cameraFollowSprite(mySprite)
