function StartLevel () {
    if (Level == 2) {
        tiles.setCurrentTilemap(tilemap`level3`)
    }
    if (Level == 3) {
        tiles.setCurrentTilemap(tilemap`level3`)
    }
    if (Level == 4) {
        tiles.setCurrentTilemap(tilemap`level3`)
    }
    if (Level == 5) {
        tiles.setCurrentTilemap(tilemap`level3`)
    }
}
let Level = 0
info.startCountdown(10)
let mySprite2 = sprites.create(assets.image`demogorgon`, SpriteKind.Enemy)
let Jones = sprites.create(img`
    ...............eeeeeee..................
    ..............eeeeeeee..................
    .............eeeeeeeeee.................
    ...............ddfdfd...................
    ...............dddddd...................
    ................ddff....................
    ...............ffddff...................
    .............fffbffbfff.................
    ...........fffeffbbffeff................
    ..........ffeeeefbbfeeeff...............
    ..........feeeeefbbfeeeeff..............
    ..........feeeeefbbfeeeeef..............
    ..........fefeeefbbfeeefef..............
    ..........fefeeefbbfeeefef..............
    ..........fefeeefbbfeeefef..............
    ..........fefeeefbbfeeefef..............
    ..........fefeeffbbffeffff..............
    ..........ffffffbbbbfff.................
    .............fbbbffbbbf.................
    .............fbbbffbbbf.................
    .............fbbffffbbf.................
    .............fbbf..fbbf.................
    .............fbbf..fbbf.................
    .............fbbf..fbbf.................
    .............fbbf..fbbf.................
    .............febf..fbef.................
    ............f11ef..fe11f................
    ...........feeeef..feeeef...............
    ...........ffffff..ffffff...............
    `, SpriteKind.Player)
controller.moveSprite(Jones)
tiles.setTilemap(tilemap`level1`)
tiles.placeOnRandomTile(Jones, assets.tile`transparency16`)
scene.cameraFollowSprite(Jones)
Level = 1
